// Command appart generates the mobile app's logo data and launcher icons from
// the terminal title art, so the phone, the terminal and the icon are all the
// same picture.
//
//	go run ./tools/appart            # from tui/: writes into ../app
//	go run ./tools/appart -preview /tmp/out   # also renders PNG previews
//	go run ./tools/appart -image ../docs/superbadger.png   # the README picture
//
// It writes:
//
//	app/src/logo/logoData.ts      the logo as tone-mapped vector runs
//	app/src/logo/iconPalette.json per-theme colors (a test checks the app agrees)
//	app/android/app/src/main/res  adaptive + legacy launcher icons, one per theme
//
// Theme colors are read from app/src/theme.tsx, never copied.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"superbadger-tui/internal/art"
)

// The app's themes, in the order Settings lists them.
var themeOrder = []string{"light", "dark", "slate", "sepia", "ember"}

func main() {
	artPath := flag.String("art", "internal/ui/splash.ans", "the enhanced title art")
	app := flag.String("app", "../app", "the app directory")
	preview := flag.String("preview", "", "also render PNG previews into this directory")
	image := flag.String("image", "", "also write the title screen, in the art's own colors, to this PNG (for the README)")
	flag.Parse()

	src, err := os.ReadFile(*artPath)
	must(err)
	logo, err := art.ExtractLogo(string(src))
	must(err)
	themeSrc, err := os.ReadFile(filepath.Join(*app, "src/theme.tsx"))
	must(err)
	pals, err := art.ParseThemes(string(themeSrc))
	must(err)
	for _, n := range themeOrder {
		if _, ok := pals[n]; !ok {
			must(fmt.Errorf("theme %q not found in theme.tsx", n))
		}
	}

	s := extractS(logo)
	must(writeLogoData(filepath.Join(*app, "src/logo/logoData.ts"), logo, s))
	must(writePalette(filepath.Join(*app, "src/logo/iconPalette.json"), pals, s))
	must(writeAndroid(filepath.Join(*app, "android/app/src/main/res"), pals, s))
	if *preview != "" {
		must(writePreviews(*preview, logo, pals, s))
	}
	if *image != "" {
		must(writePNG(*image, renderTitle(logo)))
	}
	fmt.Println("generated logo data, palette and icons from", *artPath)
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "appart:", err)
		os.Exit(1)
	}
}

// ---- the S ----

// sGlyph is the wordmark's first letter, cropped to its ink.
type sGlyph struct {
	W, H  int
	Tones []art.Tone // the distinct tones, sorted
	Grid  [][]int    // [y][x] index into Tones, or -1
	Group art.Group  // the same, as runs relative to the crop
}

func extractS(l *art.Logo) *sGlyph {
	minX, minY, maxX, maxY := art.Bounds(l.Word, l.S.X0, l.S.X1)
	g := art.GroupOf(l.Word, l.S.X0, l.S.X1, func(art.Sub) bool { return true })
	s := &sGlyph{W: maxX - minX + 1, H: maxY - minY + 1, Group: art.Group{}}
	for t, runs := range g {
		var rel art.Runs
		for i := 0; i < len(runs); i += 3 {
			rel = append(rel, runs[i]-minX, runs[i+1]-minY, runs[i+2])
		}
		s.Group[t] = rel
		s.Tones = append(s.Tones, t)
	}
	sortTones(s.Tones)
	idx := map[art.Tone]int{}
	for i, t := range s.Tones {
		idx[t] = i
	}
	s.Grid = make([][]int, s.H)
	for y := range s.Grid {
		s.Grid[y] = make([]int, s.W)
		for x := range s.Grid[y] {
			s.Grid[y][x] = -1
		}
	}
	for t, runs := range s.Group {
		for i := 0; i < len(runs); i += 3 {
			for k := 0; k < runs[i+2]; k++ {
				s.Grid[runs[i+1]][runs[i]+k] = idx[t]
			}
		}
	}
	return s
}

func sortTones(ts []art.Tone) {
	sort.Slice(ts, func(i, j int) bool {
		if ts[i].U != ts[j].U {
			return ts[i].U < ts[j].U
		}
		return ts[i].W < ts[j].W
	})
}

func sortedTones(g art.Group) []art.Tone {
	ts := make([]art.Tone, 0, len(g))
	for t := range g {
		ts = append(ts, t)
	}
	sortTones(ts)
	return ts
}

// ---- logoData.ts ----

func tonesTS(g art.Group, indent string) string {
	var b strings.Builder
	b.WriteString("[\n")
	for _, t := range sortedTones(g) {
		u, w := t.Values()
		b.WriteString(fmt.Sprintf("%s  {u: %s, w: %s, runs: [", indent, num(u), num(w)))
		for i, v := range g[t] {
			if i > 0 {
				b.WriteString(",")
			}
			b.WriteString(fmt.Sprint(v))
		}
		b.WriteString("]},\n")
	}
	b.WriteString(indent + "]")
	return b.String()
}

func num(f float64) string {
	s := fmt.Sprintf("%.4f", f)
	s = strings.TrimRight(strings.TrimRight(s, "0"), ".")
	if s == "" || s == "-" {
		return "0"
	}
	return s
}

func writeLogoData(path string, l *art.Logo, s *sGlyph) error {
	badger := art.GroupOf(l.Badger, 0, l.W, func(p art.Sub) bool { return !art.IsEye(p) })
	eye := art.GroupOf(l.Badger, 0, l.W, art.IsEye)
	var ex, ey, en float64
	for y, row := range l.Badger {
		for x, p := range row {
			if art.IsEye(p) {
				ex, ey, en = ex+float64(x)+0.5, ey+float64(y)+0.5, en+1
			}
		}
	}
	var b strings.Builder
	b.WriteString(`// GENERATED by "go run ./tools/appart" (from tui/) out of tui/internal/ui/splash.ans.
// Do not edit by hand; edit the art and regenerate.
//
// The logo is described by *tone*, not color: u is the position along the
// art's own dark→light ramp (0..4) and w how far the pixel leans toward the
// cyan accent (0..1). logoTheme.ts turns tones into a theme's colors, so one
// set of shapes serves every theme. runs is flat [x, y, length, ...] in
// sub-pixels (one sub-pixel is 1 unit wide and a bit taller; see PIXEL_ASPECT).

export interface ToneRuns {
  u: number;
  w: number;
  runs: number[];
}

export interface LogoData {
  /** width of every part, in sub-pixels */
  width: number;
  badger: {rows: number; tones: ToneRuns[]};
  /** the eye, in the badger's coordinates (drawn on top of it) */
  eye: {cx: number; cy: number; tones: ToneRuns[]};
  /** blank sub-rows between the badger and the wordmark */
  gap: number;
  /** the wordmark cut into left-to-right slices, for a staggered reveal */
  word: {rows: number; slices: {x0: number; x1: number; tones: ToneRuns[]}[]};
  /** the "S" of the wordmark, cropped, used for the app icon */
  iconS: {w: number; h: number; tones: ToneRuns[]};
}

`)
	b.WriteString(fmt.Sprintf("export const LOGO: LogoData = {\n  width: %d,\n", l.W))
	b.WriteString(fmt.Sprintf("  badger: {rows: %d, tones: %s},\n", len(l.Badger), tonesTS(badger, "  ")))
	b.WriteString(fmt.Sprintf("  eye: {cx: %s, cy: %s, tones: %s},\n", num(ex/en), num(ey/en), tonesTS(eye, "  ")))
	b.WriteString(fmt.Sprintf("  gap: %d,\n", l.Gap))
	b.WriteString(fmt.Sprintf("  word: {\n    rows: %d,\n    slices: [\n", len(l.Word)))
	for _, sp := range l.Slices {
		g := art.GroupOf(l.Word, sp.X0, sp.X1, func(art.Sub) bool { return true })
		b.WriteString(fmt.Sprintf("      {x0: %d, x1: %d, tones: %s},\n", sp.X0, sp.X1, tonesTS(g, "      ")))
	}
	b.WriteString("    ],\n  },\n")
	b.WriteString(fmt.Sprintf("  iconS: {w: %d, h: %d, tones: %s},\n};\n", s.W, s.H, tonesTS(s.Group, "  ")))
	return writeFile(path, b.String())
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// ---- iconPalette.json ----

type paletteJSON struct {
	Themes map[string]themeJSON `json:"themes"`
}

type themeJSON struct {
	Bg        string     `json:"bg"`
	Accent    string     `json:"accent"`
	Ramp      []string   `json:"ramp"`
	IconTones []toneJSON `json:"iconTones"`
}

type toneJSON struct {
	U     float64 `json:"u"`
	W     float64 `json:"w"`
	Color string  `json:"color"`
}

func writePalette(path string, pals map[string]art.Palette, s *sGlyph) error {
	out := paletteJSON{Themes: map[string]themeJSON{}}
	for _, n := range themeOrder {
		p := pals[n]
		t := themeJSON{Bg: art.ToHex(p.Bg), Accent: art.ToHex(p.Accent())}
		for _, r := range p.Ramp() {
			t.Ramp = append(t.Ramp, art.ToHex(r))
		}
		for _, tone := range s.Tones {
			u, w := tone.Values()
			t.IconTones = append(t.IconTones, toneJSON{u, w, art.ToHex(p.Color(tone))})
		}
		out.Themes[n] = t
	}
	b, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	return writeFile(path, string(b)+"\n")
}

// ---- Android resources ----

// icon geometry inside the 108dp adaptive canvas: the launcher shows only a
// 66dp circle, so the S is kept well inside it.
const (
	canvas   = 108.0
	sHeight  = 50.0
	overlapU = 0.03 // adjacent rects overlap a hair so no seams show
)

func writeAndroid(res string, pals map[string]art.Palette, s *sGlyph) error {
	ps := sHeight / float64(s.H)
	x0 := (canvas - float64(s.W)*ps) / 2
	y0 := (canvas - float64(s.H)*ps) / 2

	rectPath := func(runs art.Runs) string {
		var b strings.Builder
		for i := 0; i < len(runs); i += 3 {
			x := x0 + float64(runs[i])*ps
			y := y0 + float64(runs[i+1])*ps
			w := float64(runs[i+2])*ps + overlapU
			b.WriteString(fmt.Sprintf("M%s,%sh%sv%sh-%sz", num(x), num(y), num(w), num(ps+overlapU), num(w)))
		}
		return b.String()
	}

	colors := []string{"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- GENERATED by tui/tools/appart. One launcher-icon background per app theme. -->\n<resources>\n"}
	for _, n := range themeOrder {
		p := pals[n]
		colors = append(colors, fmt.Sprintf("    <color name=\"ic_bg_%s\">%s</color>\n", n, art.ToHex(p.Bg)))

		// foreground vector: one path per tone, filled with the theme's color
		var fg strings.Builder
		fg.WriteString("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- GENERATED by tui/tools/appart: the S of the wordmark, in the " + n + " theme. -->\n")
		fg.WriteString("<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n    android:width=\"108dp\"\n    android:height=\"108dp\"\n    android:viewportWidth=\"108\"\n    android:viewportHeight=\"108\">\n")
		for _, t := range s.Tones {
			fg.WriteString(fmt.Sprintf("    <path android:fillColor=\"%s\" android:pathData=\"%s\" />\n", art.ToHex(p.Color(t)), rectPath(s.Group[t])))
		}
		fg.WriteString("</vector>\n")
		if err := writeFile(filepath.Join(res, "drawable", "ic_launcher_fg_"+n+".xml"), fg.String()); err != nil {
			return err
		}

		adaptive := fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tui/tools/appart. API 26+ adaptive icon for the %s theme; below
     API 26 the matching mipmap-*dpi PNGs are used. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_bg_%s" />
    <foreground android:drawable="@drawable/ic_launcher_fg_%s" />
    <monochrome android:drawable="@drawable/ic_launcher_mono" />
</adaptive-icon>
`, n, n, n)
		for _, name := range []string{"ic_launcher_" + n, "ic_launcher_" + n + "_round"} {
			if err := writeFile(filepath.Join(res, "mipmap-anydpi-v26", name+".xml"), adaptive); err != nil {
				return err
			}
		}
		if err := writeLegacyPNGs(res, n, p, s); err != nil {
			return err
		}
	}
	colors = append(colors, "</resources>\n")
	if err := writeFile(filepath.Join(res, "values", "ic_theme_icons.xml"), strings.Join(colors, "")); err != nil {
		return err
	}

	// Android 13+ themed icons recolor a single-color silhouette.
	var all art.Runs
	for _, t := range s.Tones {
		all = append(all, s.Group[t]...)
	}
	mono := "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- GENERATED by tui/tools/appart: single-color S for Android 13+ themed icons. -->\n" +
		"<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n    android:width=\"108dp\"\n    android:height=\"108dp\"\n    android:viewportWidth=\"108\"\n    android:viewportHeight=\"108\">\n" +
		fmt.Sprintf("    <path android:fillColor=\"#FFFFFF\" android:pathData=\"%s\" />\n</vector>\n", rectPath(all))
	return writeFile(filepath.Join(res, "drawable", "ic_launcher_mono.xml"), mono)
}

// legacy launcher icons (API < 26) at each density
var densities = []struct {
	name string
	px   int
}{{"mdpi", 48}, {"hdpi", 72}, {"xhdpi", 96}, {"xxhdpi", 144}, {"xxxhdpi", 192}}

func writeLegacyPNGs(res, theme string, p art.Palette, s *sGlyph) error {
	for _, d := range densities {
		for _, round := range []bool{false, true} {
			img := renderIcon(p, s, d.px, round, 0.60)
			name := "ic_launcher_" + theme
			if round {
				name += "_round"
			}
			if err := writePNG(filepath.Join(res, "mipmap-"+d.name, name+".png"), img); err != nil {
				return err
			}
		}
	}
	return nil
}

func writePNG(path string, img image.Image) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return png.Encode(f, img)
}

// renderIcon draws the S on the theme's page: a rounded square, or a circle.
// heightFrac is the S's height as a fraction of the icon. 3x3 supersampling
// keeps the pixel-art edges and the shape's outline smooth.
func renderIcon(p art.Palette, s *sGlyph, size int, round bool, heightFrac float64) *image.NRGBA {
	img := image.NewNRGBA(image.Rect(0, 0, size, size))
	ps := heightFrac * float64(size) / float64(s.H)
	x0 := (float64(size) - float64(s.W)*ps) / 2
	y0 := (float64(size) - float64(s.H)*ps) / 2
	bg := p.Bg
	cols := make([]art.RGB, len(s.Tones))
	for i, t := range s.Tones {
		cols[i] = p.Color(t)
	}
	const ss = 3
	r := 0.2 * float64(size)
	for py := 0; py < size; py++ {
		for px := 0; px < size; px++ {
			var acc art.RGB
			var cover float64
			for sy := 0; sy < ss; sy++ {
				for sx := 0; sx < ss; sx++ {
					fx := float64(px) + (float64(sx)+0.5)/ss
					fy := float64(py) + (float64(sy)+0.5)/ss
					if !inShape(fx, fy, float64(size), r, round) {
						continue
					}
					cover++
					c := bg
					gx, gy := int(math.Floor((fx-x0)/ps)), int(math.Floor((fy-y0)/ps))
					if gx >= 0 && gy >= 0 && gx < s.W && gy < s.H && s.Grid[gy][gx] >= 0 {
						c = cols[s.Grid[gy][gx]]
					}
					acc[0], acc[1], acc[2] = acc[0]+c[0], acc[1]+c[1], acc[2]+c[2]
				}
			}
			if cover == 0 {
				continue
			}
			img.SetNRGBA(px, py, color.NRGBA{
				R: uint8(acc[0]/cover + 0.5), G: uint8(acc[1]/cover + 0.5), B: uint8(acc[2]/cover + 0.5),
				A: uint8(255 * cover / (ss * ss)),
			})
		}
	}
	return img
}

func inShape(x, y, size, r float64, round bool) bool {
	if round {
		c := size / 2
		return (x-c)*(x-c)+(y-c)*(y-c) <= c*c
	}
	// rounded square
	cx := math.Min(math.Max(x, r), size-r)
	cy := math.Min(math.Max(y, r), size-r)
	return (x-cx)*(x-cx)+(y-cy)*(y-cy) <= r*r
}

// ---- previews ----

// The terminal's sub-pixels are 3 wide by 4 tall (a cell is 2 wide x 3 tall
// sub-pixels and about 1:2), which is how the logo is drawn in the app too.
const (
	pixW = 3
	pixH = 4
)

func writePreviews(dir string, l *art.Logo, pals map[string]art.Palette, s *sGlyph) error {
	scale := 2
	for _, n := range themeOrder {
		p := pals[n]
		rows := len(l.Badger) + l.Gap + len(l.Word)
		img := image.NewNRGBA(image.Rect(0, 0, (l.W+8)*pixW*scale, (rows+6)*pixH*scale))
		draw.Draw(img, img.Bounds(), &image.Uniform{toNRGBA(p.Bg)}, image.Point{}, draw.Src)
		fill := func(px [][]art.Sub, yOff int) {
			for y, row := range px {
				for x, sub := range row {
					if !sub.On {
						continue
					}
					c := toNRGBA(p.Color(art.ToneOf(sub.C)))
					r := image.Rect((x+4)*pixW*scale, (y+yOff+3)*pixH*scale, (x+5)*pixW*scale, (y+yOff+4)*pixH*scale)
					draw.Draw(img, r, &image.Uniform{c}, image.Point{}, draw.Src)
				}
			}
		}
		fill(l.Badger, 0)
		fill(l.Word, len(l.Badger)+l.Gap)
		if err := writePNG(filepath.Join(dir, "logo_"+n+".png"), img); err != nil {
			return err
		}
		if err := writePNG(filepath.Join(dir, "icon_"+n+".png"), renderIcon(p, s, 256, false, 0.60)); err != nil {
			return err
		}
		if err := writePNG(filepath.Join(dir, "icon_round_"+n+".png"), renderIcon(p, s, 256, true, 0.60)); err != nil {
			return err
		}
	}
	return nil
}

func toNRGBA(c art.RGB) color.NRGBA {
	return color.NRGBA{R: uint8(c[0] + 0.5), G: uint8(c[1] + 0.5), B: uint8(c[2] + 0.5), A: 255}
}

// renderTitle draws the title screen (badger + wordmark) exactly as the
// terminal shows it: the art's own colors on its own navy page, each sub-pixel
// 3x4 units (the terminal's proportions) at 3x scale. No fonts or terminal are
// involved, so it is the same on every machine.
func renderTitle(l *art.Logo) *image.NRGBA {
	const scale = 3
	const margin = 8 // sub-pixels of page around the logo
	pw, ph := pixW*scale, pixH*scale
	rows := len(l.Badger) + l.Gap + len(l.Word)
	img := image.NewNRGBA(image.Rect(0, 0, (l.W+2*margin)*pw, (rows+2*margin)*ph))
	draw.Draw(img, img.Bounds(), &image.Uniform{toNRGBA(art.Page)}, image.Point{}, draw.Src)
	fill := func(px [][]art.Sub, yOff int) {
		for y, row := range px {
			for x, sub := range row {
				if !sub.On {
					continue
				}
				r := image.Rect((x+margin)*pw, (y+yOff+margin)*ph, (x+margin+1)*pw, (y+yOff+margin+1)*ph)
				draw.Draw(img, r, &image.Uniform{toNRGBA(sub.C)}, image.Point{}, draw.Src)
			}
		}
	}
	fill(l.Badger, 0)
	fill(l.Word, len(l.Badger)+l.Gap)
	return img
}
