root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/superbadger-server ./cmd/superbadger-server"
  bin = "./tmp/superbadger-server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 200

[log]
  time = false

[misc]
  clean_on_exit = true
