-- +goose Up
--
-- API auth tokens, generated by the `badger token generate` CLI (see
-- cmd/badger). Only a SHA-256 hash of the token is stored — the plaintext is
-- shown once at generation time and never persisted — so a leaked database
-- doesn't hand out usable credentials. `last4` is kept purely so `badger
-- token list` can show which token is which without ever re-displaying a
-- full token.

CREATE TABLE `auth_tokens` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`label` text NOT NULL DEFAULT '',
	`token_hash` text NOT NULL,
	`last4` text NOT NULL,
	`created_at` datetime NOT NULL,
	`last_used_at` datetime
);

CREATE UNIQUE INDEX `idx_auth_tokens_hash` ON `auth_tokens`(`token_hash`);

-- +goose Down
DROP TABLE `auth_tokens`;
