#!/usr/bin/env bash
#
# gen-keystore.sh — one-time local release signing setup.
#
# Generates release/release.keystore (a real Android upload/signing
# keystore) and release/keystore.env (its passwords), so release.sh has
# something to sign with. Run once; re-running refuses to overwrite an
# existing keystore, since replacing it would make every previously-issued
# release un-upgradable in place (Android refuses to install an update signed
# by a different key over an app installed from the old one).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYSTORE_FILE="$SCRIPT_DIR/release.keystore"
ENV_FILE="$SCRIPT_DIR/keystore.env"
ALIAS="superbadger"

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
info()  { printf '\033[36m%s\033[0m\n' "$*"; }
die()   { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v keytool >/dev/null 2>&1 || die "'keytool' not found on PATH (part of a JDK)"

if [[ -f "$KEYSTORE_FILE" || -f "$ENV_FILE" ]]; then
	die "$KEYSTORE_FILE or $ENV_FILE already exists — refusing to overwrite signing material in place"
fi

password="$(head -c 24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)"

bold "==> Generating release keystore"
keytool -genkeypair \
	-v \
	-keystore "$KEYSTORE_FILE" \
	-alias "$ALIAS" \
	-keyalg RSA \
	-keysize 2048 \
	-validity 10000 \
	-storepass "$password" \
	-keypass "$password" \
	-dname "CN=super-badger, OU=super-badger, O=super-badger, L=, ST=, C=US"

cat > "$ENV_FILE" <<EOF
# super-badger mobile release signing — LOCAL ONLY, gitignored (see
# release/.gitignore). Do not commit. Generated by gen-keystore.sh on $(date -Iseconds).
#
# If you also wire up CI (.github/workflows), these three values are what go
# into the repo's Actions secrets SUPERBADGER_KEYSTORE_PASSWORD /
# SUPERBADGER_KEY_ALIAS / SUPERBADGER_KEY_PASSWORD, and the base64 of
# release.keystore goes into a SUPERBADGER_KEYSTORE_BASE64 secret.

SUPERBADGER_KEYSTORE_FILE=$KEYSTORE_FILE
SUPERBADGER_KEYSTORE_PASSWORD=$password
SUPERBADGER_KEY_ALIAS=$ALIAS
SUPERBADGER_KEY_PASSWORD=$password
EOF
chmod 600 "$ENV_FILE"

info "wrote $KEYSTORE_FILE and $ENV_FILE"
info "run 'npm run release' (from app/) or './release/release.sh' next"
